services:
  - type: web
    name: mercadinho-caminhar-api
    runtime: docker
    plan: starter
    region: virginia
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mercadinho-caminhar-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: TOKEN_EXPIRE_MINUTES
        value: "600"

databases:
  - name: mercadinho-caminhar-db
    databaseName: netobebidas
    user: neto
    plan: basic-256mb
    region: virginia
    postgresMajorVersion: "18"
